### ISSUE TITLE
USER STORY: <To finish the Poll>

### ISSUE THREAD

**Issue by Sazzzel** [Sazzzel/Love-Running#5]
In order to **automatically hide the poll ** as a **administrator**, I can **pick the expiry date while publishing the poll**

**Comment by Sazzzel** [comment]
### **Accepting Criteria**

1. The poll should disappear at 11:59PM on the target date.
2. The real estate of the Poll should be reserved on the homepage. a message that says "Stay tuned, a new poll is coming soon" should appear if no other poll is active.
3. The administrator expiry date should be at least 3 days after the current date.

**Comment by Sazzzel** [comment]
### **Tasks**

- [ ] Update the admin module view: the poll design (HTML and CSS) to include date picker.
- [ ] Update the website view: show "stay tuned, a new poll is coming."
- [ ] Create a JavaScript function to validate the expiry date is at least 3 days.
- [ ] Create a job to check expired Polls everyday at 11:59PM and hide them.
- [ ] Update the controller function.
- [ ] Update the test scripts.
- [ ] Test the functionality.

**Comment by Sazzzel** [comment]
### **Story Points:** 5

-  We need to do major design changes on the home page and the administrator side
- We need to create a scheduled job to run at 11:59 PM to check for expired polls
- We need to adjust the view, the model and the controller.
